# InfoVis - DataSet Region Metropolitana

In [41]:
import matplotlib.pyplot as plt 
import pandas as pd
import numpy as np

# Solo ignora los avisos de que algo está obsoleto, pero deja los demás activos
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

### Lectura de Datos Precio Mayorista fruta hortaliza desde 2022 a 2026

In [42]:
fruta_2022 = pd.read_csv('precio_mayorista_fruta-hortaliza_2022.csv', decimal=',')
fruta_2023 = pd.read_csv('precio_mayorista_fruta-hortaliza_2023.csv', decimal=',')
fruta_2024 = pd.read_csv('precio_mayorista_fruta-hortaliza_2024.csv', decimal=',')
fruta_2025 = pd.read_csv('precio_mayorista_fruta-hortaliza_2025.csv', decimal=',')
fruta_2026 = pd.read_csv('precio_mayorista_fruta-hortaliza_2026.csv', decimal=',')

In [43]:
fruta_data = pd.concat([
    fruta_2022.dropna(how = 'all'),
    fruta_2023.dropna(how = 'all'),
    fruta_2024.dropna(how = 'all'),
    fruta_2025.dropna(how = 'all'),
    fruta_2026.dropna(how = 'all'),
], ignore_index = True).loc[:, ['Fecha','ID region','Region','Mercado','Subsector',
                                'Producto','Variedad / Tipo','Calidad','Unidad de comercializacion',
                                'Origen','Volumen','Precio minimo','Precio maximo','Precio promedio']]

fruta_data.head(10)

,Fecha,ID region,Region,Mercado,Subsector,Producto,Variedad / Tipo,Calidad,Unidad de comercializacion,Origen,Volumen,Precio minimo,Precio maximo,Precio promedio
0,2022-01-03,5,Región de Valparaíso,Femacal de La Calera,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,$/docena de atados (6 kilos),Provincia de Quillota,230,2300.0,2500.0,2395.6521
1,2022-01-03,4,Región de Coquimbo,Terminal La Palmera de La Serena,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,"$/atado 1,5 a 2 kilos",Provincia del Elquí,2400,450.0,500.0,475.0000
2,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,$/docena de atados,Región Metropolitana,60,18000.0,18000.0,18000.0000
3,2022-01-03,15,Región de Arica y Parinacota,Agrícola del Norte S.A. de Arica,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,"$/atado 2,5 a 3 kilos",Región de Arica y Parinacota,200,1900.0,2000.0,1950.0000
4,2022-01-03,4,Región de Coquimbo,Terminal La Palmera de La Serena,Hortalizas y tubérculos,Acelga,Sin especificar,Segunda,"$/atado 1,5 a 2 kilos",Provincia del Elquí,1400,350.0,400.0,375.0000
5,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Acelga,Sin especificar,Segunda,$/docena de atados,Región Metropolitana,30,16000.0,16000.0,16000.0000
6,2022-01-03,5,Región de Valparaíso,Femacal de La Calera,Hortalizas y tubérculos,Achicoria,Sin especificar,Primera,$/caja 16 unidades,Provincia de Quillota,110,6500.0,7000.0,6772.7272
7,2022-01-03,13,Región Metropolitana de Santiago,Vega Central Mapocho de Santiago,Hortalizas y tubérculos,Ají,Inferno,Primera,$/caja 15 kilos,Provincia de Huasco,43,22000.0,25000.0,23534.8837
8,2022-01-03,4,Región de Coquimbo,Terminal La Palmera de La Serena,Hortalizas y tubérculos,Ají,Americana (o),Primera,$/caja 15 kilos,Provincia de Limarí,400,17000.0,18000.0,17500.0000
9,2022-01-03,5,Región de Valparaíso,Femacal de La Calera,Hortalizas y tubérculos,Ají,Americana (o),Primera,$/caja 15 kilos,Provincia de Quillota,38,23000.0,23000.0,23000.0000

In [44]:
frutas_rm = fruta_data[fruta_data['Region'] == 'Región Metropolitana de Santiago']

### DataSet de Frutas solo de la Region Metropolitana

In [45]:
#print(fruta_data.dtypes) saber el tipo de dato de cada columna
frutas_rm.head(10)

,Fecha,ID region,Region,Mercado,Subsector,Producto,Variedad / Tipo,Calidad,Unidad de comercializacion,Origen,Volumen,Precio minimo,Precio maximo,Precio promedio
2,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,$/docena de atados,Región Metropolitana,60,18000.0,18000.0,18000.0000
5,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Acelga,Sin especificar,Segunda,$/docena de atados,Región Metropolitana,30,16000.0,16000.0,16000.0000
7,2022-01-03,13,Región Metropolitana de Santiago,Vega Central Mapocho de Santiago,Hortalizas y tubérculos,Ají,Inferno,Primera,$/caja 15 kilos,Provincia de Huasco,43,22000.0,25000.0,23534.8837
10,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Ají,Americana (o),Primera,$/saco 25 kilos,Región Metropolitana,22,40000.0,45000.0,42727.2727
11,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Ají,Chilena(o),Primera,$/saco 25 kilos,Región Metropolitana,44,45000.0,50000.0,48181.8181
17,2022-01-03,13,Región Metropolitana de Santiago,Vega Central Mapocho de Santiago,Hortalizas y tubérculos,Ají,Inferno,Segunda,$/caja 15 kilos,Provincia de Huasco,16,20000.0,20000.0,20000.0000
18,2022-01-03,13,Región Metropolitana de Santiago,Vega Central Mapocho de Santiago,Hortalizas y tubérculos,Ajo,Chino,Primera,$/caja 10 kilos,China,520,17500.0,18000.0,17750.0000
19,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Ajo,Chino,Primera,$/caja 10 kilos,China,1500,16500.0,17000.0,16700.0000
25,2022-01-03,13,Región Metropolitana de Santiago,Vega Central Mapocho de Santiago,Hortalizas y tubérculos,Ajo,Chino,Primera,$/malla 10 kilos,China,340,18000.0,18500.0,18250.0000
28,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Albahaca,Sin especificar,Primera,$/docena de matas,Región Metropolitana,1090,3500.0,5000.0,4568.8073

In [46]:
frutas_rm["Producto"].unique()

<StringArray>
[              'Acelga',                  'Ají',                  'Ajo',
             'Albahaca',                 'Apio',      'Arándano (blue)',
              'Plátano',            'Berenjena',            'Betarraga',
                'Breva',              'Brócoli',               'Camote',
              'Cebolla',           'Ciboulette',               'Cereza',
               'Choclo',             'Cilantro',             'Coliflor',
              'Damasco',              'Durazno',             'Espinaca',
            'Frambuesa',             'Frutilla',             'Jengibre',
              'Lechuga',                'Limón',                'Mango',
              'Manzana',                'Melón',                 'Mora',
              'Naranja',             'Nectarín',                'Palta',
                 'Papa',      'Pepino ensalada',                 'Pera',
              'Perejil',             'Pimiento',                 'Piña',
       'Poroto granado',         'Poroto verde',              'Repollo',
               'Sandia',               'Tomate',            'Zanahoria',
              'Zapallo',     'Zapallo italiano',             'Cebollín',
              'Ciruela',              'Orégano',                  'Uva',
            'Mandarina',         'Arveja Verde',             'Rabanito',
            'Achicoria',               'Puerro',               'Pomelo',
                 'Kiwi',                 'Tuna',         'Pepino dulce',
                 'Coco',            'Membrillo',                 'Higo',
            'Alcachofa',                 'Haba',              'Granada',
           'Espárragos',        'Pera asiática', 'Bruselas (repollito)',
                'Caqui',            'Chirimoya',               'Papaya',
              'Níspero',             'Maracuyá',    'Fruto del paraíso']
Length: 75, dtype: str

## Analisis Del DataSet

¿Qué quieres saber de tus datos?
¿Qué tipo de "visualización" deberías usar?
¿Lo que observas tiene sentido?

In [47]:
#Tipos de Productos 
categoria = set()
for i in frutas_rm['Subsector']:
    categoria.add(i)

print(categoria)

{'Frutas', 'Hortalizas y tubérculos'}

###  Pregunta 2: ¿Los productos con mayor cantidad de volumen tienen una ganacia mas alta en epocas especificas del año?

Crearemos nuevas columnas que contemplen los meses del año que corresponde cada fecha y asi agruparlo por estacion y una columnaa que me permita saebr la ganancia estimada, PERO Con los datos actuales no se puede calcular la ganancia neta, ya que no tenemos el costo de produccion o del producto, pero si calcular que productos de mayor volumen generan mas ingresos brutos por epoca del año.

In [48]:

# 1. Convertir la columna a formato fecha nativo (súper rápido si ya tiene formato Año-Mes-Día)
frutas_rm['Fecha'] = pd.to_datetime(frutas_rm['Fecha'])

# 2. Extraer el mes y el número matemático MMDD (Mes * 100 + Día) de forma vectorizada
# Ej: 20 de marzo -> 320, 21 de junio -> 621, 21 de diciembre -> 1221
frutas_rm['Month'] = frutas_rm['Fecha'].dt.month
mmdd = frutas_rm['Fecha'].dt.month * 100 + frutas_rm['Fecha'].dt.day

# 3. Definir las reglas lógicas para todas las filas al mismo tiempo
condiciones = [
    (mmdd >= 1221) | (mmdd < 320),  # Verano: 21 Dic al 19 Mar
    (mmdd >= 320) & (mmdd < 621),   # Otoño: 20 Mar al 20 Jun
    (mmdd >= 621) & (mmdd <= 921),  # Invierno: 21 Jun al 21 Sep
    (mmdd >= 922) & (mmdd < 1221)   # Primavera: 22 Sep al 20 Dic
]

opciones = ['Verano', 'Otoño', 'Invierno', 'Primavera']

# 4. np.select evalúa las condiciones de golpe y asigna la estación en milisegundos
frutas_rm['Season'] = np.select(condiciones, opciones, default='Fecha inválida')


#Columna de ingreso bruto
frutas_rm['Ingreso Bruto'] = frutas_rm['Volumen'] * (frutas_rm['Precio promedio'] / 10000)

frutas_rm

,Fecha,ID region,Region,Mercado,Subsector,Producto,Variedad / Tipo,Calidad,Unidad de comercializacion,Origen,Volumen,Precio minimo,Precio maximo,Precio promedio,Month,Season,Ingreso Bruto
2,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,$/docena de atados,Región Metropolitana,60,18000.0,18000.0,18000.0000,1,Verano,108.000000
5,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Acelga,Sin especificar,Segunda,$/docena de atados,Región Metropolitana,30,16000.0,16000.0,16000.0000,1,Verano,48.000000
7,2022-01-03,13,Región Metropolitana de Santiago,Vega Central Mapocho de Santiago,Hortalizas y tubérculos,Ají,Inferno,Primera,$/caja 15 kilos,Provincia de Huasco,43,22000.0,25000.0,23534.8837,1,Verano,101.200000
10,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Ají,Americana (o),Primera,$/saco 25 kilos,Región Metropolitana,22,40000.0,45000.0,42727.2727,1,Verano,94.000000
11,2022-01-03,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Ají,Chilena(o),Primera,$/saco 25 kilos,Región Metropolitana,44,45000.0,50000.0,48181.8181,1,Verano,212.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821565,2026-04-10,13,Región Metropolitana de Santiago,Vega Central Mapocho de Santiago,Hortalizas y tubérculos,Zapallo italiano,Sin especificar,Primera,$/caja 60 unidades,Región Metropolitana,250,8000.0,10000.0,9000.0000,4,Otoño,225.000000
821575,2026-04-10,13,Región Metropolitana de Santiago,Vega Central Mapocho de Santiago,Hortalizas y tubérculos,Cebollín,Sin especificar,Primera,$/paquete 36 unidades,Región Metropolitana,430,3200.0,3600.0,3400.0000,4,Otoño,146.200000
821576,2026-04-10,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Cebollín,Sin especificar,Primera,$/paquete 36 unidades,Región Metropolitana,2700,3300.0,3500.0,3418.5185,4,Otoño,922.999995
821579,2026-04-10,13,Región Metropolitana de Santiago,Vega Central Mapocho de Santiago,Hortalizas y tubérculos,Cebollín,Sin especificar,Segunda,$/paquete 36 unidades,Región Metropolitana,340,2600.0,3000.0,2800.0000,4,Otoño,95.200000
821580,2026-04-10,13,Región Metropolitana de Santiago,Mercado Mayorista Lo Valledor de Santiago,Hortalizas y tubérculos,Cebollín,Sin especificar,Segunda,$/paquete 36 unidades,Región Metropolitana,800,2600.0,2600.0,2600.0000,4,Otoño,208.000000

###  Pregunta 3: ¿Lavariabilidad de los precios es mas presente en distribuidoras o mercados mayoristas que en un comercio mas local?